
camera_topic: /head_xtion/rgb/image_raw
depth_camera_topic: /head_xtion/depth/image_raw
yolo_topic: /darknet_ros/bounding_boxes
people_topic: /people_tracker_filter
legs_topic: /leg_tracker_measurements
entities_marker_topic: /entities_marker
leg_distance: 1
leg_tolerance: 0.6
camera_tolerance: 1.0
people_tolerance: 2.0
entity_decay: 0.01
entity_cumulation: 0.2
entity_friction: 0.8
name_weight: 2.0
person_weight: 2.0
color_weight: 0.2
gender_weight: 0.6
publication_threshold: 0.2
normalise_probability: false
max_probability: 1
leg_probability_ratio: 0.01
speed_ratio: 8