camera_topic: /darknet/sync_rgb_image
depth_camera_topic: /darknet/sync_depth_image
yolo_topic: /darknet_ros/bounding_boxes
people_topic: /people_tracker_filter
legs_topic: /leg_tracker_measurements
entities_marker_topic: /entities_marker

# Entity kinematic parameters
entity_decay: 0.02
entity_friction: 0.7
publication_threshold: 0.2
max_probability: 1
speed_ratio: 2.5

# post merge parameters
post_merge_tolerence: 1.0
post_merge_max_distance: 0.2
post_merge_person_tolerence_ratio: 0.8
post_merge_person_max_distance: 0.8

# leg parameters
leg_merge_tolerance: 1.0
leg_merge_max_distance: 0.8
leg_merge_cumulation: 0.005

# Camera parameters
camera_merge_tolerance: 1.4
camera_merge_max_distance: 0.4
camera_merge_cumulation: 0.9
people_merge_tolerance: 1.5
people_merge_max_distance: 1
people_merge_cumulation: 0.9

# Weights parameters
name_weight: 1
color_weight: 0.2
gender_weight: 0.5