
camera_topic: /head_xtion/rgb/image_raw
depth_camera_topic: /head_xtion/depth/image_raw
yolo_topic: /darknet_ros/bounding_boxes
people_topic: /people_tracker_filter
legs_topic: /people_tracker_measurements
entities_marker_topic: /entities_marker
leg_distance: 1
leg_tolerance: 0.6
camera_tolerance: 0.8
people_tolerance: 0.8
entity_decay: 0.99
entity_friction: 0.9
name_weight: 1.0
person_weight: 1.0
color_weight: 0.6
gender_weight: 0.6
publication_threshold: 0.5
normalise_probability: false